# Generated by Django 3.2.8 on 2021-10-24 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_of_joining', models.DateField()),
                ('candidate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.candidate')),
            ],
        ),
    ]
