# Generated by Django 3.2.8 on 2021-10-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='enrollment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
