# Generated by Django 3.2.8 on 2021-10-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_invoice_enrollment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='enrollment_id',
        ),
    ]
