# Generated by Django 3.2.8 on 2021-10-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211025_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='candidate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='enrollment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
